### PR TITLE
fix ps() printing when selecting columns?

### PR DESCRIPTION
**Pull request by maelle**
cf #16

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I think we should just define a `[` methods, and drop the class, always. 

This used to work because tibble's `[` method used to drop extra classes, but it keeps them now.

**Comment by maelle** [comment]
Aaah ok that would be less hacky.

Note to self, this is how to add such a method https://github.com/tidyverse/tibble/blob/71b8ff698a6bb19c0ec8d9f5f0d1f70cb47969be/R/subsetting.R#L96

**Comment by gaborcsardi** [comment]
This should be much simpler, just drop all the classes, except for `data.frame` and then call `NextMethod`.

**Comment by gaborcsardi** [comment]
Actually, just drop the `pkg_search_result` class, and keep the rest.

**Comment by gaborcsardi** [comment]
Maybe just calling `NextMethod` does that already?

**Comment by maelle** [comment]
But you need to drop the class in a method defined like above?

**Comment by gaborcsardi** [comment]
Maybe `NextMethod` drops the class already, IDK.

**Comment by maelle** [comment]
I just need to find out where to put `NextMethod` then :slightly_smiling_face:

**Comment by maelle** [comment]
i.e. do you mean

```r

  if(!all(c("score", "package", "version", "title", "description", "date", 
                 "maintainer_name", "maintainer_email", "revdeps", "downloads_last_month", 
                 "license", "url", "bugreports", "package_data") %in%
          names(x))) {
    NextMethod("print", x)
  } else {
  }
```

in my current hack or something simpler or creating a `[` method? I'm a bit lost.

**Comment by gaborcsardi** [comment]
No, just define a method like this, in the package:
```r
#' @export

`[.pkg_search_result` <- function(x, i, j, drop = FALSE) {
  class(x) <- setdiff(class(x), "pkg_search_result")
  NextMethod("[")
}
```

**Comment by gaborcsardi** [comment]
This has the additional benefit of converting to a tibble with `[]` indexing, which I like:

```r
ps("color")[]
```

And this makes sense, because once you index the search results object, it might not be a valid search result object any more, so dropping the class is the right thing here.

**Comment by maelle** [comment]
:sparkles: :+1:

**Comment by maelle** [comment]
no need to add docs, or?

**Comment by gaborcsardi** [comment]
No need. This is how it used to work before the tibble update, anyway.

**Comment by maelle** [comment]
@gaborcsardi is this ready to merge or do you have further comments? :smile_cat:

**Comment by gaborcsardi** [comment]
Thanks much, approved!

**Pull request merged**
