### PR TITLE
add option to skip version check for cran_package()

### PR DESCRIPTION
**Pull request by ErdaradunGaztea**
Sometimes packages have version names that don't fit into `is_package_version()` requirements. For example, `xtable`, which consistently names its versions in `1.X-X` pattern. These names are returned by `cran_package_history()` and I'd expect them to be usable in `cran_package()` no matter the form (in fact, I use this very pipeline in `deepdep` package).

Since I don't want to break backwards compatibility, I added `check_version` argument with default `TRUE` value that allows the user to skip `is_package_version()` check. Documented and tested the behaviour to make sure everything works.

Side note, 4 tests fail now (and they did before I changed anything in the code), because `igraph` is no more the top search result, it's `crayon` now.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! This is however a bug, `pkgsearch:::is_package_version` should not fail for valid version numbers.

**Comment by ErdaradunGaztea** [comment]
Honestly, as mentioned in #39, valid version numbers can be almost anything. While there are guidelines for semantical versioning, not all packages follow them and, ultimately, the package's author has the last say on how to name the version. Thus, the implementation would basically look like `is_package_version <- function(pkg) TRUE` (maybe except for checking if `pkg` is a single string).

**Comment by gaborcsardi** [comment]
> Honestly, as mentioned in #39, valid version numbers can be almost anything.

For very old packages, yes. Otherwise in the past 20 years or so they have to look like this:
```r
❯ base::.standard_regexps()$valid_package_version
[1] "([[:digit:]]+[.-]){1,}[[:digit:]]+"
```

But yeah, we can just drop that check, and only check if it is a non-NA string scalar.

**Comment by ErdaradunGaztea** [comment]
Ahh, didn't know that, interesting! I'm on board with dropping that, should I implement this check?

**Comment by gaborcsardi** [comment]
YEs, please. Thanks!

**Comment by ErdaradunGaztea** [comment]
I saw you using `assertthat`, so I reused their function `is.string()` with added (also theirs) `noNA()` check.

**Comment by ErdaradunGaztea** [comment]
Checking the failing tests...
- [ ] `cran_package_history()` fails because v1.2.10 of `igraph` was published and the sorting would place it between v1.2.1 and v1.2.2
- [ ] I don't know why `cran_package()` fails on Windows, it seems it must be somehow dropping `crandb_file_date` and `date` fields, but I have Windows (no shaming plz!) and the test was based on the result I got, so I'm confused here

**Comment by ErdaradunGaztea** [comment]
Okay, I believe I might have fixed failing tests. I went as far as submitting [versionsort](https://github.com/ErdaradunGaztea/versionsort) to CRAN, but for now I copied version sorting code into `R/versort_utils.R`.

**Comment by gaborcsardi** [comment]
Thanks, and I am sorry for the long wait. I ended up solving this a different way.

**Pull request closed without merging**
